apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: microservice-gateway
spec:
    selector:
        istio: ingressgateway # use istio default controller
    servers:
    - port:
          number: 80
          name: http
          protocol: HTTP
      hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: microservice
spec:
    hosts:
    - "*"
    gateways:
    - microservice-gateway
    http:
    - match:
      - uri:
            prefix: /
      route:
      - destination:
            host: {{ include "charts.fullname" . }}.microservice.svc.cluster.local
            port:
                number: {{ .Values.service.port }}
