- pipeline: infra
  trigger_mode: ON_EVERY_PUSH
  ref_name: master
  ref_type: BRANCH
  trigger_condition: ALWAYS
  actions:
  - action: "terraform apply"
    type: "BUILD"
    working_directory: "/buddy/microservice/infra"
    docker_image_name: "library/ubuntu"
    docker_image_tag: "18.04"
    execute_commands:
    - "echo 'credentials \"app.terraform.io\" {\ntoken = '$TOKEN_TERRAFORM_IO'\n}' > ~/.terraformrc"
    - "openssl enc -in ../env/microservices.json.enc -out ../env/microservices.json -d -aes256 -pass pass:$PASWORD_CREDENTIAL_FILE"
    - "terraform init && terraform apply --auto-approve"
    - "rm -rf ../env/microservices.json"
    - "rm -rf ~/.terraformrc"
    setup_commands:
    - "apt-get update"
    - "apt-get --assume-yes install wget unzip"
    - "wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip"
    - "unzip ./terraform_0.12.6_linux_amd64.zip -d /usr/local/bin/"
    - "terraform -v"
    mount_filesystem_path: "/buddy/microservice"
    shell: "BASH"
    trigger_condition: "ALWAYS"
  - action: "ansible worker"
    type: "BUILD"
    working_directory: "/buddy/microservice"
    docker_image_name: "ansible/ansible"
    docker_image_tag: "ubuntu1604"
    execute_commands:
    - "echo ${ANSBILE_HOSTS} > hosts"
    - "ansible-playbook -i hosts infra/ansible/initial.yml"
    - "ansible-playbook -i hosts infra/ansible/kube-dependencies.yml"
    - "ansible-playbook -i hosts infra/ansible/master-node.yml"
    - "ansible-playbook -i hosts infra/ansible/workers-node.yml"
    mount_filesystem_path: "/buddy/microservice"
    shell: "BASH"
    trigger_condition: "ALWAYS"
