apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
#    - host: config.sanlovie.com
#      http:
#        paths:
#          - backend:
#              serviceName: consul
#              servicePort: 8500
    - host: tunnel.sanlovie.com
      http:
        paths:
          - backend:
              serviceName: micro-tunnel
              servicePort: 30036
#    - host: api.sanlovie.com
#      http:
#        paths:
#          - backend:
#              serviceName: movie-api-microservices
#              servicePort: 3000