apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-tunnel
  labels:
    micro: runtime
    name: micro-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-tunnel
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-tunnel
        micro: runtime
    spec:
      containers:
        - name: tunnel
          env:
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: "etcd-cluster-client"
          args:
            - tunnel
          image: micro/micro:v1.14.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: tunnel-port
