apiVersion: v1
kind: Service
metadata:
  name: micro-tunnel
  namespace: default
  labels:
    name: micro-tunnel
    micro: runtime
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: UDP
      targetPort: 8083
  selector:
    name: micro-tunnel
    micro: runtime