- hosts: all
  become: yes
  tasks:
    - name: create the 'haduong' user
      user: name=haduong append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'haduong' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'haduong ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the haduong user
      authorized_key: user=haduong key="{{item}}"
      with_file:
        - ../../env/id_rsa.pub
