- hosts: all
  become: yes
  tasks:
    - name: create the 'duongha' user
      user: name=duongha append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'duongha' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'duongha ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the duongha user
      authorized_key: user=duongha key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
