apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    service: consul
spec:
  selector:
    app: consul
  type: ClusterIP
  ports:
    - port: 8500
      name: http
      targetPort: 8500

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.7.2
          ports:
            - containerPort: 8500
              name: http