// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/movie.proto

package micro_models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId" json:"contact_id,omitempty"`
	Tags                 string   `protobuf:"bytes,3,opt,name=tags" json:"tags,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	Source               int64    `protobuf:"varint,5,opt,name=source" json:"source,omitempty"`
	TicketCreatedAt      int64    `protobuf:"varint,6,opt,name=ticket_created_at,json=ticketCreatedAt" json:"ticket_created_at,omitempty"`
	TicketUpdatedAt      int64    `protobuf:"varint,7,opt,name=ticket_updated_at,json=ticketUpdatedAt" json:"ticket_updated_at,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	AppCode              string   `protobuf:"bytes,10,opt,name=app_code,json=appCode" json:"app_code,omitempty"`
	Platform             string   `protobuf:"bytes,11,opt,name=platform" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_movie_e47d31c6e20ff680, []int{0}
}
func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (dst *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(dst, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Movie) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *Movie) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Movie) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Movie) GetSource() int64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *Movie) GetTicketCreatedAt() int64 {
	if m != nil {
		return m.TicketCreatedAt
	}
	return 0
}

func (m *Movie) GetTicketUpdatedAt() int64 {
	if m != nil {
		return m.TicketUpdatedAt
	}
	return 0
}

func (m *Movie) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Movie) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Movie) GetAppCode() string {
	if m != nil {
		return m.AppCode
	}
	return ""
}

func (m *Movie) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func init() {
	proto.RegisterType((*Movie)(nil), "micro.models.Movie")
}

func init() { proto.RegisterFile("models/movie.proto", fileDescriptor_movie_e47d31c6e20ff680) }

var fileDescriptor_movie_e47d31c6e20ff680 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xd5, 0xb4, 0x4d, 0x93, 0x03, 0x81, 0xb8, 0x01, 0x19, 0xa4, 0x4a, 0x15, 0x53, 0xc5,
	0x50, 0x06, 0x9e, 0xa0, 0xea, 0xc4, 0xc0, 0x52, 0x89, 0x39, 0x32, 0x3e, 0x83, 0x2c, 0x1a, 0xce,
	0x72, 0x2e, 0xbc, 0x22, 0xaf, 0x85, 0x38, 0x87, 0x90, 0x2d, 0xff, 0xff, 0x7d, 0xf9, 0x65, 0x1b,
	0xb0, 0x65, 0xf2, 0xa7, 0xee, 0xa1, 0xe5, 0xaf, 0xe0, 0x77, 0x31, 0xb1, 0x30, 0x9e, 0xb7, 0xc1,
	0x25, 0xde, 0x65, 0x72, 0xf7, 0x5d, 0xc0, 0xf2, 0xf9, 0x97, 0xe2, 0x05, 0x14, 0x81, 0xcc, 0x6c,
	0x33, 0xdb, 0xce, 0x8f, 0x45, 0x20, 0x5c, 0x03, 0x38, 0xfe, 0x14, 0xeb, 0xa4, 0x09, 0x64, 0x8a,
	0xcd, 0x6c, 0x5b, 0x1f, 0xeb, 0xa1, 0x79, 0x22, 0x44, 0x58, 0x88, 0x7d, 0xef, 0xcc, 0x5c, 0x81,
	0x7e, 0xe3, 0x35, 0x94, 0x9d, 0x58, 0xe9, 0x3b, 0xb3, 0xd0, 0x99, 0x21, 0x69, 0xcf, 0x7d, 0x72,
	0xde, 0x2c, 0x87, 0x5e, 0x13, 0xde, 0xc3, 0x95, 0x04, 0xf7, 0xe1, 0xa5, 0x71, 0xc9, 0x5b, 0xf1,
	0xd4, 0x58, 0x31, 0xa5, 0x2a, 0x97, 0x19, 0x1c, 0x72, 0xbf, 0x97, 0x89, 0xdb, 0x47, 0xfa, 0x73,
	0x57, 0x53, 0xf7, 0x25, 0xf7, 0x7b, 0xd1, 0xa3, 0xff, 0x0f, 0x56, 0x2a, 0xd5, 0x6e, 0x9c, 0x5a,
	0x03, 0x4c, 0x36, 0xea, 0x8c, 0xfb, 0xf1, 0xef, 0x1b, 0xa8, 0x6c, 0x8c, 0x8d, 0x63, 0xf2, 0x06,
	0xf4, 0x76, 0x2b, 0x1b, 0xe3, 0x81, 0xc9, 0xe3, 0x2d, 0x54, 0xf1, 0x64, 0xe5, 0x8d, 0x53, 0x6b,
	0xce, 0x14, 0x8d, 0xf9, 0xb5, 0xd4, 0xe7, 0x7d, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x50,
	0x07, 0x9c, 0x74, 0x01, 0x00, 0x00,
}
